version: '3.8'

services:
  
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT:-5432}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST_DOCKER:-db}
    networks:
      - journey

  db:
    image: postgres:16.2-alpine3.19
    container_name: api-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
    networks:
      - journey

networks:
  journey:
    driver: bridge
  


    