apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-deployment
  labels:
    app: journey
spec:
  replicas: 5
  selector:
    matchLabels:
      app: journey
  template:
    metadata:
      labels:
        app: journey
    spec:
      containers:
        - name: api-journey
          image: kejorox/nlw-journey-devops:3cc24b0
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "300m"